livy.server.port = 8998
livy.spark.master = spark://spark-master:7077
livy.spark.deploy-mode = cluster
livy.file.local-dir-whitelist = /opt/bitnami/spark/jobs
livy.server.session.config.whitelist = spark.executor.instances,spark.executor.cores,spark.executor.memory,spark.executor.memoryOverhead,spark.driver.memory,spark.network.timeout,spark.executor.heartbeatInterval,spark.sql.shuffle.partitions,spark.sql.files.maxRecordsPerFile,spark.hadoop.fs.s3a.*,spark.jars.packages