# ==== postgres_dim_customer_vld.yaml ====
table: dim_customer
primary_key: customer_key

schema:
  - name: customer_key
    type: string
  - name: name
    type: string
  - name: contact_no
    type: string
  - name: nid
    type: string

validation_rules:
  - id: not_null_customer_key
    rule: not_null
    columns: ["customer_key"]
